import type { AIReport, Project, Task, TaskStatus } from "@/lib/types";

export const sampleProject: Project = {
  id: "commitbet-alpha",
  title: "Ship CommitBet waitlist sprint",
  description: "A 14-day sprint to launch the first public CommitBet waitlist and evidence workflow demo.",
  goal: "Launch a credible waitlist page with a working signup flow, demo evidence, and a final review narrative.",
  status: "active",
  startDate: "2026-06-18",
  endDate: "2026-07-01",
  successCriteria: [
    "Public landing page is live",
    "Waitlist form stores submissions",
    "Daily evidence is attached to every critical task",
    "Final demo can be reviewed by an outside founder",
  ],
  pledgePool: 180,
  successScore: 74,
  aiRiskInsight: {
    level: "medium",
    summary: "Evidence is strong, but the demo script is trending late.",
    why: "Two critical tasks are due in the next 48 hours and only one has reviewable evidence.",
  },
  members: [
    {
      id: "mara",
      name: "Mara Chen",
      email: "mara@example.com",
      role: "Product lead",
      strengths: ["scope", "copy", "customer interviews"],
      contributionScore: 88,
      pledgePoints: 60,
    },
    {
      id: "ion",
      name: "Ion Petraitis",
      email: "ion@example.com",
      role: "Frontend engineer",
      strengths: ["Next.js", "UI systems", "analytics"],
      contributionScore: 82,
      pledgePoints: 60,
    },
    {
      id: "sana",
      name: "Sana Ortiz",
      email: "sana@example.com",
      role: "AI workflow",
      strengths: ["review rubrics", "prompting", "QA"],
      contributionScore: 71,
      pledgePoints: 60,
    },
  ],
  tasks: [
    {
      id: "task-landing",
      projectId: "commitbet-alpha",
      title: "Build waitlist landing page",
      description: "Create the public page that explains CommitBet and captures early access signups.",
      ownerId: "ion",
      ownerName: "Ion Petraitis",
      status: "approved",
      priority: "critical",
      dueDate: "2026-06-22",
      acceptanceCriteria: ["Responsive hero is live", "CTA leads to signup", "Core flow is explained without gambling language"],
      expectedEvidenceTypes: ["demo", "screenshot", "link"],
      evidence: [
        {
          id: "ev-landing",
          taskId: "task-landing",
          type: "demo",
          title: "Production preview",
          description: "Preview link with mobile and desktop screenshots attached.",
          url: "https://commitbet.example.com",
          submittedAt: "2026-06-22",
          qualityScore: 92,
        },
      ],
      reviewHistory: [{ id: "rev-landing", taskId: "task-landing", reviewer: "Mara Chen", status: "approved", comment: "Matches the criteria and tone.", createdAt: "2026-06-22" }],
    },
    {
      id: "task-evidence",
      projectId: "commitbet-alpha",
      title: "Evidence submission flow",
      description: "Make task proof easy to submit and review from mobile.",
      ownerId: "ion",
      ownerName: "Ion Petraitis",
      status: "submitted",
      priority: "high",
      dueDate: "2026-06-26",
      acceptanceCriteria: ["Users can add a link", "Evidence has a short explanation", "Peer reviewer sees criteria next to proof"],
      expectedEvidenceTypes: ["screenshot", "link", "document"],
      evidence: [
        {
          id: "ev-evidence",
          taskId: "task-evidence",
          type: "screenshot",
          title: "Mobile proof form",
          description: "Shows the fast evidence capture flow with task context.",
          submittedAt: "2026-06-25",
          qualityScore: 78,
        },
      ],
      reviewHistory: [],
    },
    {
      id: "task-report",
      projectId: "commitbet-alpha",
      title: "AI final report narrative",
      description: "Draft the final project report with confidence, reasoning, and human confirmation.",
      ownerId: "sana",
      ownerName: "Sana Ortiz",
      status: "in_progress",
      priority: "high",
      dueDate: "2026-06-28",
      acceptanceCriteria: ["Includes member contribution scores", "Explains pledge recommendation", "Requires human confirmation"],
      expectedEvidenceTypes: ["document", "link"],
      evidence: [],
      reviewHistory: [],
    },
    {
      id: "task-interviews",
      projectId: "commitbet-alpha",
      title: "Interview three small teams",
      description: "Validate whether evidence-based commitments solve a real pain for teams.",
      ownerId: "mara",
      ownerName: "Mara Chen",
      status: "needs_changes",
      priority: "medium",
      dueDate: "2026-06-24",
      acceptanceCriteria: ["Three interviews completed", "Notes include abandonment trigger", "Insights are summarized"],
      expectedEvidenceTypes: ["document", "link"],
      evidence: [
        {
          id: "ev-interviews",
          taskId: "task-interviews",
          type: "document",
          title: "Interview notes",
          description: "Two completed interviews and one scheduled call.",
          submittedAt: "2026-06-24",
          qualityScore: 61,
        },
      ],
      reviewHistory: [{ id: "rev-interviews", taskId: "task-interviews", reviewer: "Sana Ortiz", status: "needs_changes", comment: "Need the third completed interview before approval.", createdAt: "2026-06-24" }],
    },
  ],
  dailyLogs: [
    {
      id: "log-1",
      projectId: "commitbet-alpha",
      author: "Ion Petraitis",
      date: "2026-06-25",
      completed: "Submitted the mobile evidence flow and attached screenshots.",
      relatedTaskIds: ["task-evidence"],
      timeSpentMinutes: 95,
      evidenceLink: "https://example.com/proof/mobile-flow",
      blockers: "Needs reviewer copy.",
      nextSteps: "Tighten the empty state and add review actions.",
    },
    {
      id: "log-2",
      projectId: "commitbet-alpha",
      author: "Sana Ortiz",
      date: "2026-06-24",
      completed: "Drafted the AI report rubric and confidence language.",
      relatedTaskIds: ["task-report"],
      timeSpentMinutes: 70,
      nextSteps: "Map report sections to database values.",
    },
  ],
};

export const sampleProjects: Project[] = [
  sampleProject,
  {
    ...sampleProject,
    id: "mobile-proof",
    title: "Mobile daily evidence beta",
    status: "draft",
    pledgePool: 90,
    successScore: 41,
    aiRiskInsight: {
      level: "high",
      summary: "The plan has not been started and member availability is uneven.",
      why: "No approved task exists yet and the commitment window is only seven days.",
    },
  },
];

export const sampleTasksByStatus = sampleProject.tasks.reduce<Record<TaskStatus, Task[]>>(
  (groups, task) => {
    groups[task.status].push(task);
    return groups;
  },
  {
    todo: [],
    in_progress: [],
    submitted: [],
    approved: [],
    needs_changes: [],
    rejected: [],
    disputed: [],
  },
);

export const sampleAIReport: AIReport = {
  projectSummary: "The sprint produced a credible waitlist page and a reviewable evidence workflow. The strongest proof is the live demo and reviewer-approved landing page.",
  successCriteriaEvaluation: [
    { criterion: "Public landing page is live", status: "met", comment: "Verified with preview link and screenshots." },
    { criterion: "Waitlist form stores submissions", status: "partial", comment: "Form UI is complete; production storage still needs an integration check." },
    { criterion: "Daily evidence is attached to every critical task", status: "partial", comment: "Two critical tasks have evidence, one still needs final proof." },
  ],
  taskStatistics: { planned: 12, approved: 7, needsChanges: 2, rejected: 0, disputed: 1, late: 2 },
  memberContributionScores: [
    { memberId: "mara", name: "Mara Chen", score: 88, summary: "Strong scoping and customer validation, with one interview still incomplete." },
    { memberId: "ion", name: "Ion Petraitis", score: 84, summary: "Delivered the main UI and evidence flow with clear supporting proof." },
    { memberId: "sana", name: "Sana Ortiz", score: 76, summary: "Created the AI review rubric and handled dispute framing." },
  ],
  evidenceQuality: 82,
  delayAnalysis: "The project stayed mostly on track. Late work is concentrated around research completion and final report polish.",
  disputeSummary: "One dispute was opened over incomplete interviews. The evidence suggests partial credit, not rejection.",
  recommendation: "Release 85% of the virtual pledge pool and roll the remaining 15% into a follow-up commitment.",
  recommendationWhy: "Most success criteria were met or partially met, evidence quality is high, and remaining gaps are bounded.",
  confidenceScore: 81,
};
